version: "3.8"

services:
  app:
    build: .
    ports:
      - "5300:5300"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: "3306"
      DATABASE_USER: root
      DATABASE_PASSWORD: testpassword
      DATABASE_NAME: daftListing
    volumes:
      - .:/app
    
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: daftListing
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
