version: "3.8"

services:
  server:
    build: . # local image
    #image: ghcr.io/allannastin/gdp4-backend:latest
    ports:
      - "5300:5300"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: "3306"
      DATABASE_USER: root
      DATABASE_PASSWORD: testpassword
      DATABASE_NAME: daftListing
      SECRET_KEY: "test_secret_key"
    volumes:
      - .:/app
    
  db:
    build: ./db # local image
    # image: ghcr.io/allannastin/gdp4-db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: daftListing
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
