version: "3.8"

services:
  app:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: testpassword
      DATABASE_NAME: mydatabase
    volumes:
      - .:/app
    
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
