name: Build & Push Backend and Database

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(?!.*\[no-build]).*$'
          flags: "gms"
          error: "Force no-build!"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push backend
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: |
          TAG=$(if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then echo "latest"; else echo "${GITHUB_REF##*/}"; fi)
          docker build \
            -t ghcr.io/allannastin/gdp4-backend:$TAG \
            ./backend
          docker push ghcr.io/allannastin/gdp4-backend:$TAG

      - name: Build and push database
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: |
          TAG=$(if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then echo "latest"; else echo "${GITHUB_REF##*/}"; fi)
          docker build \
            -t ghcr.io/allannastin/gdp4-db:$TAG \
            ./backend/db
          docker push ghcr.io/allannastin/gdp4-db:$TAG
